# Site settings
title: Fluent Bit
email: eduardo@calyptia.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://fluentbit.io"
twitter_username: fluentbit
github_username:  fluent

# Blog
permalink: /blog/:year/:month/:day/:title/

# Build settings
#markdown: kramdown
markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data"]

flb_major       : "1.7"
flb_version     : 1.7.2
flb_release_date: Mar 03, 2021
